version: '3'
services:
    pycontw-2014:
        build: .
        container_name: pycontw-2014
        hostname: pycontw-2014
        ports:
            - 8014:80

    pycontw-2014-redis:
        image: redis:latest
        container_name: pycontw-2014-redis
        hostname: pycontw-2014-redis

networks:
    default:
        external:
            name: pycontw-net
